language: python
python:
  - 3.6
before_install:
  - python --version
  - pip install -U pip 
  - pip install -U pytest
  - time
  - numpy<=1.15.4
  - pandas<=1.0.3
  - matplotlib
  - seaborn<=0.11.1
  - bs4
  - requests<=2.25.1
  - pip install codecov
script: 
  - pytest tests/*
after_success:
  - codecov 
