language: python
python:
  - 3.6
before_install:
  - python --version
  - pip install -U pip 
  - pip install -U pytest
  - pip install numpy<=1.15.4
  - pip install pandas<=1.0.3
  - pip install matplotlib
  - pip install seaborn<=0.11.1
  - pip install bs4
  - pip install requests<=2.25.1
  - pip install codecov
script: 
  - pytest tests/*
after_success:
  - codecov 
